lesson1 comleted
ilya-xbsoftware/webix-jet-start pull request #1
Opened 2021-04-16 12:01 UTC by ilya-xbsoftware

2021-04-16 12:50 UTC, ekosiy approved these changes

2021-04-16 13:48 UTC, Zwillinge requested changes

2021-04-16 13:48 UTC, Zwillinge commented on sources/views/contacts.js
> +			this.$scope.$$("contactForm").clear();
нехорошо. clearMessage и successSave заданы так, что this внутри метода класса указывает не на класс, а на кнопку. тебе надо было задавать их как `click: ()=>this.clearMessage()`

2021-04-16 13:48 UTC, Zwillinge commented on sources/views/data.js
> +				{ template: "<span class='webix_icon wxi-trash deleteBtn'></span>", css:"deleteBtn" }
ты передаешь в колонки одну и ту же trash icon, тем самым дублируя код. здесь надо передать минимум, а всё сделать в config Datatable модуля.  колонку с удалением там можно было добавить точно 

чтобы совсем красиво. ты здесь передаешь 

`new Datatable(this.app, "", countries, ["Name"])`
`new Datatable(this.app, "", countries, ["Status, Icon"])`

а внутри формируешь columns

2021-04-16 13:48 UTC, Zwillinge commented on sources/views/settings.js
> +		const btn = this.$$("toggle");
значение toggle написано на toggle. зачем дублировать этой в label? если так хочется задать лейбл, пуcть это будет Language

2021-04-16 14:36 UTC, ilya-xbsoftware commented on sources/views/settings.js
> +		const btn = this.$$("toggle");
Исправил

2021-04-16 14:36 UTC, ilya-xbsoftware commented on sources/views/data.js
> +				{ template: "<span class='webix_icon wxi-trash deleteBtn'></span>", css:"deleteBtn" }
Все переделал ! 
стало намного приятней.

2021-04-16 14:36 UTC, ilya-xbsoftware commented on sources/views/contacts.js
> +			this.$scope.$$("contactForm").clear();
Исправил.

2021-04-16 19:52 UTC, Zwillinge commented on sources/views/settings.js
> +		const btn = this.$$("toggle");
статический лейбл Language, который не меняется при изменения значения кнопки. russian или english будет же написано на самой кнопке

2021-04-16 19:56 UTC, Zwillinge commented on sources/views/data.js
> +				{ template: "<span class='webix_icon wxi-trash deleteBtn'></span>", css:"deleteBtn" }
мелочи остались:

- кнопка добавления хранится в переменной sortController 
- в _columnsRender  почти одинаковые объекты в map return, можно было б
`{id:`${field}`, header:`${field}`, editor:"text", fillspace: index === array.length - 1}`

2021-04-17 08:33 UTC, ilya-xbsoftware commented on sources/views/data.js
> +				{ template: "<span class='webix_icon wxi-trash deleteBtn'></span>", css:"deleteBtn" }
sortController - это я назвал так форму. В webix-start у нас тоже такая задача была. И я её назвал, точно также. 
Кнопка лежит в форме. Я предполагал, что это форма, которая добавляет и ищет значения. Поэтому для меня это sortController.

2021-04-17 08:41 UTC, ilya-xbsoftware commented on sources/views/data.js
> +				{ template: "<span class='webix_icon wxi-trash deleteBtn'></span>", css:"deleteBtn" }
{id:${field}, header:${field}, editor:"text", fillspace: index === array.length - 1} 

Классное решение ) Спасибо. Я поправил.

2021-04-17 08:42 UTC, ilya-xbsoftware commented on sources/views/settings.js
> +		const btn = this.$$("toggle");
сделал Label статическим.

2021-04-17 09:19 UTC, Zwillinge commented on sources/views/data.js
> +				{ template: "<span class='webix_icon wxi-trash deleteBtn'></span>", css:"deleteBtn" }
> сортировать по value in view:"text" 

такого не было в start. там была фильтрация по тому, что пользователь вводил в поле. для сортировки были кнопки

в реальном проекте вещи должны называться своими именами, чтобы дргуие программисты понимали назначение элементов

2021-04-17 09:20 UTC, Zwillinge approved these changes

2021-04-17 09:20 UTC, merged