Lesson2
ilya-xbsoftware/webix-jet-start pull request #2
Opened 2021-04-19 08:36 UTC by ilya-xbsoftware

2021-04-19 09:37 UTC, igr-ik commented on sources/locales/ru.js
> +	"Language:": "Язык:",
В конце строк локалей, лучше не оставлять знаки препинания, если этот знак действительно не будет во всех местах приложения. В данном случае, знак ":", в одном месте нужен будет, а в другом нет.

2021-04-19 09:37 UTC, igr-ik commented on sources/views/contactsForm.js
> +			return false;
Не понятен смысл этого ретурна

2021-04-19 11:50 UTC, ilya-xbsoftware commented on sources/locales/ru.js
> +	"Language:": "Язык:",
понял, исправил !

2021-04-19 11:58 UTC, igr-ik approved these changes

2021-04-19 12:25 UTC, Zwillinge requested changes

2021-04-19 12:25 UTC, Zwillinge commented on sources/models/collections.js
> +import { contacts } from "models/contacts";
не надо так делать. каждая модель отвечает за определенный сет данных (который соответствует таблице на сервере например). какая-то за контакты, какая-то за статусы и т.д. ты объединил коллекции, но смешал разные данные,  а так делать не стоит

2021-04-19 12:25 UTC, Zwillinge commented on sources/locales/messages.js
> +	country:"The field must not be empty",
локали по правилам хранятся так: один язык - один файл
такдже не вижу где переводы этих лейблов на русский?

2021-04-19 12:26 UTC, Zwillinge commented
по приложению многт вопросов, носложно ревьюить то, что со старта вылетает с ошибкой
![err](https://user-images.githubusercontent.com/2278891/115236015-85769300-a123-11eb-8185-90c6be4932f6.png)

2021-04-19 14:53 UTC, ilya-xbsoftware commented on sources/locales/messages.js
> +	country:"The field must not be empty",
Создал папку  constants переместил туда messages. 
Все переводы сделал.

2021-04-19 14:54 UTC, ilya-xbsoftware commented on sources/models/collections.js
> +import { contacts } from "models/contacts";
понял. переделал.

2021-04-19 15:12 UTC, Zwillinge commented on sources/locales/messages.js
> +	country:"The field must not be empty",
а зачем, чем лейблы в messages отличаются от всех остальных? пусть локали хранятся в локалях, зачем запутывать код?

2021-04-19 15:13 UTC, Zwillinge commented
npm run lint

2021-04-19 15:25 UTC, Zwillinge requested changes

2021-04-19 15:25 UTC, Zwillinge commented on sources/views/contacts.js
> +		this.on(this.list, "onAfterSelect", (id) =>{
события можно назначать на Init, ready имеет смысл только если мы хотим работать с subview и нам надо убиедиться что они созданы. но слушать onAfterDelete избыточно, у тебя есть обработчик удаления, из которого ты можешь вызвать метод класса deleteItem, в нем удалить элемент и вызвать show

для show тебе не надо искать первый id или какой-либо другой, этим должен заниматься urlChange и только. 

ты там просто проверяешь что select и удаляемый айтем совпадабт и вызываешь this.show("../contacts"); без параметра.

2021-04-19 15:25 UTC, Zwillinge commented on sources/views/contacts.js
> +			this.setParam("id", 1, true);
не надо сеттить здеcь параметр. этим занимается onAfterSelect. на urlChange тебе надо взять id из урла или id первого контакта, проверить наличие такого элемента в коллекции и вызвать list.select. а уже тот по onAfterselect отправит параметр в url

2021-04-19 15:25 UTC, Zwillinge commented on sources/views/contactsForm.js
> +		const id = this.getParam("id");
если его нет, берем первый

2021-04-19 15:25 UTC, Zwillinge commented on sources/views/contactsForm.js
> +			contacts.parse(values);
вообще-то обновление записи это updateItem

2021-04-19 15:25 UTC, Zwillinge commented on sources/windows/popup.js
> +import FormView from "views/contactsForm";
это вью не используется, насколько я вижу

2021-04-19 15:25 UTC, Zwillinge commented on sources/views/contacts.js
> +		contacts.add({
а выбрать? надо сделать select, чтобы id нового контакта попало в url, а его данные -  форму

2021-04-19 15:29 UTC, ilya-xbsoftware commented on sources/locales/messages.js
> +	country:"The field must not be empty",
понял, сделал.

2021-04-19 15:35 UTC, ilya-xbsoftware commented on sources/windows/popup.js
> +import FormView from "views/contactsForm";
убрал.

2021-04-19 16:05 UTC, ilya-xbsoftware commented on sources/views/contacts.js
> +		this.on(this.list, "onAfterSelect", (id) =>{
разобрался ! Спасибо :))

2021-04-19 16:19 UTC, ilya-xbsoftware commented on sources/views/contactsForm.js
> +		const id = this.getParam("id");
разобрался, исправил

2021-04-19 16:37 UTC, ilya-xbsoftware commented on sources/views/contacts.js
> +		contacts.add({
Добавил.

2021-04-19 16:39 UTC, ilya-xbsoftware commented on sources/views/contactsForm.js
> +			contacts.parse(values);
исправил

2021-04-19 16:40 UTC, Zwillinge commented on sources/views/contactsForm.js
> +		const id = this.getParam("id");
`this.list.select(firstId);` - ты предполагаешь что в листе всегда есть данные на ините, но это не так. надо проверять

2021-04-19 16:43 UTC, Zwillinge commented on sources/views/contacts.js
> +		this.on(this.list, "onAfterSelect", (id) =>{
у тебя нет return false при удалении (должен быть вне конфирма, чтобы по клику на крестик, айтем не выбирался)

когда его добавишь, убедись, что show("top/contacts") вызывается только если удален выбранный контакт

2021-04-19 16:45 UTC, Zwillinge requested changes

2021-04-19 16:45 UTC, Zwillinge commented on sources/views/contacts.js
> +			autoheight:true,
autoheight делает высоту листа равной сумме высот его айтемов. 
если ты добавишь много данных, то кнопка уползет с экрана и станет недоступна
да и неудобно, что она прыгает постоянно. она должна быть прижата к низу

2021-04-19 16:45 UTC, ilya-xbsoftware commented on sources/views/contacts.js
> +			autoheight:true,
понял

2021-04-19 16:50 UTC, ilya-xbsoftware commented on sources/views/contactsForm.js
> +		const id = this.getParam("id");
исправил. Согласен надо проверять все время

2021-04-19 17:41 UTC, ilya-xbsoftware commented on sources/views/contactsForm.js
> +		const id = this.getParam("id");
проверяю через count().

2021-04-19 17:56 UTC, Zwillinge commented on sources/views/contactsForm.js
> +		const id = this.getParam("id");
достаточно обычного exists, нет смыла создавать под count отдельную переменную

2021-04-20 06:27 UTC, ilya-xbsoftware commented on sources/views/contactsForm.js
> +		const id = this.getParam("id");
переписал

2021-04-20 06:28 UTC, ilya-xbsoftware commented on sources/views/contacts.js
> +		this.on(this.list, "onAfterSelect", (id) =>{
добавил,  проверил, убедился что show("top/contacts") вызывается при удалении выбранного контакта

2021-04-20 07:51 UTC, Zwillinge commented on sources/views/contactsForm.js
> +		const id = this.getParam("id");
мелочь, но тоже стоит поправить: ты уже сохранил item в currentId, а потом при parse снова его находишь вместо того, чтобы переиспользовать переменную

2021-04-20 08:03 UTC, ilya-xbsoftware commented on sources/views/contactsForm.js
> +		const id = this.getParam("id");
Поправил

2021-04-20 08:17 UTC, Zwillinge approved these changes

2021-04-20 08:24 UTC, merged